/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTransfersRouteImport } from './routes/portal.transfers'
import { Route as PortalTransactionsRouteImport } from './routes/portal.transactions'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalLoansRouteImport } from './routes/portal.loans'
import { Route as PortalInstrumentsRouteImport } from './routes/portal.instruments'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalCryptoRouteImport } from './routes/portal.crypto'
import { Route as PortalBeneficiariesRouteImport } from './routes/portal.beneficiaries'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminInstrumentsRouteImport } from './routes/admin.instruments'
import { Route as AdminImpersonateRouteImport } from './routes/admin.impersonate'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTransfersRoute = PortalTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTransactionsRoute = PortalTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoansRoute = PortalLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInstrumentsRoute = PortalInstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCryptoRoute = PortalCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBeneficiariesRoute = PortalBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => PortalRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstrumentsRoute = AdminInstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpersonateRoute = AdminImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/impersonate': typeof AdminImpersonateRoute
  '/admin/instruments': typeof AdminInstrumentsRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/support': typeof AdminSupportRoute
  '/portal/beneficiaries': typeof PortalBeneficiariesRoute
  '/portal/crypto': typeof PortalCryptoRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/instruments': typeof PortalInstrumentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/transfers': typeof PortalTransfersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/impersonate': typeof AdminImpersonateRoute
  '/admin/instruments': typeof AdminInstrumentsRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/support': typeof AdminSupportRoute
  '/portal/beneficiaries': typeof PortalBeneficiariesRoute
  '/portal/crypto': typeof PortalCryptoRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/instruments': typeof PortalInstrumentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/transfers': typeof PortalTransfersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/mobile': typeof MobileRoute
  '/portal': typeof PortalRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/impersonate': typeof AdminImpersonateRoute
  '/admin/instruments': typeof AdminInstrumentsRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/support': typeof AdminSupportRoute
  '/portal/beneficiaries': typeof PortalBeneficiariesRoute
  '/portal/crypto': typeof PortalCryptoRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/instruments': typeof PortalInstrumentsRoute
  '/portal/loans': typeof PortalLoansRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/transfers': typeof PortalTransfersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/mobile'
    | '/portal'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/impersonate'
    | '/admin/instruments'
    | '/admin/loans'
    | '/admin/rbac'
    | '/admin/support'
    | '/portal/beneficiaries'
    | '/portal/crypto'
    | '/portal/dashboard'
    | '/portal/instruments'
    | '/portal/loans'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/transfers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/mobile'
    | '/portal'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/impersonate'
    | '/admin/instruments'
    | '/admin/loans'
    | '/admin/rbac'
    | '/admin/support'
    | '/portal/beneficiaries'
    | '/portal/crypto'
    | '/portal/dashboard'
    | '/portal/instruments'
    | '/portal/loans'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/transfers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/mobile'
    | '/portal'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/impersonate'
    | '/admin/instruments'
    | '/admin/loans'
    | '/admin/rbac'
    | '/admin/support'
    | '/portal/beneficiaries'
    | '/portal/crypto'
    | '/portal/dashboard'
    | '/portal/instruments'
    | '/portal/loans'
    | '/portal/settings'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/transfers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MobileRoute: typeof MobileRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/transfers': {
      id: '/portal/transfers'
      path: '/transfers'
      fullPath: '/portal/transfers'
      preLoaderRoute: typeof PortalTransfersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/transactions': {
      id: '/portal/transactions'
      path: '/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof PortalTransactionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/loans': {
      id: '/portal/loans'
      path: '/loans'
      fullPath: '/portal/loans'
      preLoaderRoute: typeof PortalLoansRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/instruments': {
      id: '/portal/instruments'
      path: '/instruments'
      fullPath: '/portal/instruments'
      preLoaderRoute: typeof PortalInstrumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/crypto': {
      id: '/portal/crypto'
      path: '/crypto'
      fullPath: '/portal/crypto'
      preLoaderRoute: typeof PortalCryptoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/beneficiaries': {
      id: '/portal/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/portal/beneficiaries'
      preLoaderRoute: typeof PortalBeneficiariesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instruments': {
      id: '/admin/instruments'
      path: '/instruments'
      fullPath: '/admin/instruments'
      preLoaderRoute: typeof AdminInstrumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impersonate': {
      id: '/admin/impersonate'
      path: '/impersonate'
      fullPath: '/admin/impersonate'
      preLoaderRoute: typeof AdminImpersonateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminImpersonateRoute: typeof AdminImpersonateRoute
  AdminInstrumentsRoute: typeof AdminInstrumentsRoute
  AdminLoansRoute: typeof AdminLoansRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminSupportRoute: typeof AdminSupportRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminImpersonateRoute: AdminImpersonateRoute,
  AdminInstrumentsRoute: AdminInstrumentsRoute,
  AdminLoansRoute: AdminLoansRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminSupportRoute: AdminSupportRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalBeneficiariesRoute: typeof PortalBeneficiariesRoute
  PortalCryptoRoute: typeof PortalCryptoRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalInstrumentsRoute: typeof PortalInstrumentsRoute
  PortalLoansRoute: typeof PortalLoansRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTransactionsRoute: typeof PortalTransactionsRoute
  PortalTransfersRoute: typeof PortalTransfersRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBeneficiariesRoute: PortalBeneficiariesRoute,
  PortalCryptoRoute: PortalCryptoRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalInstrumentsRoute: PortalInstrumentsRoute,
  PortalLoansRoute: PortalLoansRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTransactionsRoute: PortalTransactionsRoute,
  PortalTransfersRoute: PortalTransfersRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MobileRoute: MobileRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
